# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

variables:
  pythonPath: '/usr/src/Python-3.11.3/python'  # Path to the manually installed Python version
  #pythonVersion: '3.11'  # Specify the Python version to use

steps:
- script: |
    $(pythonPath) -m pip install --upgrade pip  # Upgrade pip
    $(pythonPath) -m pip install -r requirements.txt  # Install dependencies from requirements.txt
  displayName: 'Install dependencies'

# Run unit tests defined in code
- script: |
    $(pythonPath) -m pytest test_test1.py
  displayName: 'pytest'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-$(python.version).zip
    replaceExistingArchive: true

# Publish the artifacts folder so that it can be used in the release pipeline to deploy application
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
